[Login]
HandlePowerKey=ignore
HandleSuspendKey=suspend
HandleSuspendKeyLongPress=suspend
HandleHibernateKey=suspend
HandleHibernateKeyLongPress=suspend
HandleLidSwitch=ignore
HandleLidSwitchExternalPower=ignore
HandleLidSwitchDocked=ignore
IdleAction=ignore
SleepOperation=suspend
