general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = bash ~/.config/hypr/scripts/power.sh resume
    inhibit_sleep = 3
}

listener {
    timeout = 300
    on-timeout = bash ~/.config/hypr/scripts/power.sh idle battery
    on-resume = bash ~/.config/hypr/scripts/power.sh resume
}

listener {
    timeout = 900
    on-timeout = bash ~/.config/hypr/scripts/power.sh idle ac
    on-resume = bash ~/.config/hypr/scripts/power.sh resume
}
