[Appearance]
color_scheme_path=/home/victor/.config/qt6ct/colors/monocraft.conf
custom_palette=true
icon_theme=Papirus-Dark
standard_dialogs=default
style=Fusion

[Fonts]
fixed="Monocraft Nerd Font,10,-1,5,50,0,0,0,0,0"
general="Monocraft Nerd Font,10,-1,5,50,0,0,0,0,0"
