general {
    hide_cursor = true
    immediate_render = true
    fail_timeout = 1500
}

auth {
    pam:enabled = true
    pam:module = hyprlock
    fingerprint:enabled = true
    fingerprint:ready_message = Scan fingerprint or enter password
    fingerprint:present_message = Scanning fingerprint
    fingerprint:retry_delay = 250
}

background {
    monitor =
    color = rgba(00000000)
}

label {
    monitor =
    text = $TIME
    color = rgb(67ffeb)
    font_family = Monocraft Nerd Font
    font_size = 52
    position = 0, 120
    halign = center
    valign = center
}

label {
    monitor =
    text = Hi, $USER
    color = rgb(f8f8f2)
    font_family = Monocraft Nerd Font
    font_size = 18
    position = 0, 42
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 360, 58
    outline_thickness = 3
    dots_size = 0.25
    dots_spacing = 0.25
    outer_color = rgb(67ffeb)
    inner_color = rgb(191919)
    font_color = rgb(f8f8f2)
    fail_color = rgb(ff025f)
    check_color = rgb(a2f300)
    placeholder_text = <span foreground="##404040">Password or fingerprint</span>
    fail_text = <span foreground="##ff025f">Authentication failed</span>
    font_family = Monocraft Nerd Font
    position = 0, -45
    halign = center
    valign = center
}
