Section "InputClass"
    Identifier "system-keyboard"
    MatchIsKeyboard "on"
    Option "XkbLayout" "us,bg"
    Option "XkbVariant" ",bas_phonetic"
    Option "XkbOptions" "grp:win_space_toggle"
EndSection
