#!/usr/bin/env python3
"""Generate the checked-in stock Waybar config; no generation runs at startup."""

import argparse
import json
from pathlib import Path


def workspace(number):
    label = f"custom/workspace#{number}"
    apps = f"hyprland/workspaces#apps{number}"
    return {
        f"group/workspace{number}": {
            "orientation": "horizontal",
            "modules": [label, apps],
        },
        label: {
            "return-type": "json",
            "format": "{text}",
            "exec": 'cat "$XDG_RUNTIME_DIR/dots-waybar-'
                    f'$HYPRLAND_INSTANCE_SIGNATURE/$WAYBAR_OUTPUT_NAME-{number}.json"',
            "signal": 9,
            "exec-on-event": False,
            "on-click": f"hyprctl dispatch 'function() dots.view_at_cursor({number}) end'",
        },
        apps: {
            "format": "{windows}",
            "all-outputs": False,
            "active-only": False,
            "show-special": False,
            "ignore-workspaces": [f"^(?![0-9]*{number}$).*$"],
            "enable-bar-scroll": False,
            "workspace-taskbar": {
                "enable": True,
                "update-active-window": True,
                "format": "{icon}",
                "icon-size": 16,
                "icon-theme": ["Papirus-Dark", "Adwaita"],
                "orientation": "horizontal",
                "on-click-window": "~/.config/waybar/focus-window.sh {address} {button}",
            },
        },
    }


def config():
    result = {
        "layer": "top",
        "position": "top",
        "start_hidden": True,
        "height": 30,
        "spacing": 3,
        "on-sigusr1": "toggle",
        "modules-left": [f"group/workspace{n}" for n in range(1, 10)],
        "modules-center": ["clock"],
        "modules-right": ["tray", "battery"],
        "clock": {"format": "{:%Y-%m-%d  %H:%M}"},
        "battery": {
            "states": {"warning": 30, "critical": 15},
            "format": "{capacity}%",
            "format-charging": "{capacity}%",
        },
        "tray": {"spacing": 8},
    }
    for number in range(1, 10):
        result.update(workspace(number))
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the config is stale")
    args = parser.parse_args()
    path = Path(__file__).resolve().parent.parent / ".config/waybar/config.jsonc"
    rendered = "// Generated by scripts/generate-waybar.py; edit that file instead.\n"
    rendered += json.dumps(config(), indent=2) + "\n"
    if args.check:
        if path.read_text() != rendered:
            raise SystemExit("Waybar config is stale; run python3 scripts/generate-waybar.py")
        print("Waybar config is up to date")
    else:
        path.write_text(rendered)


if __name__ == "__main__":
    main()
