live_config_reload = true

[colors.bright]
black = "#191919"
blue = "#35ddff"
cyan = "#67ffeb"
green = "#a2f300"
magenta = "#9359ff"
red = "#ff025f"
white = "#f8f8f2"
yellow = "#ffb247"

[colors.normal]
black = "#404040"
blue = "#35ddff"
cyan = "#67ffeb"
green = "#a2f300"
magenta = "#9359ff"
red = "#ff025f"
white = "#f8f8f2"
yellow = "#ffb247"

[colors.primary]
background = "#191919"
foreground = "#f8f8f2"

[cursor]
style = "Underline"
vi_mode_style = "Underline"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR="1.0"

[font]
size = 10

[font.bold]
family = "Monocraft Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Monocraft Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Monocraft Nerd Font"
style = "Italic"

[font.normal]
family = "Monocraft Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
dynamic_padding = true
opacity = 0.9
