general {
    hide_cursor = true
    immediate_render = true
}

auth {
    pam:enabled = true
    pam:module = hyprlock
    fingerprint:enabled = true
}

background {
    monitor =
    color = rgb(191919)
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    color = rgb(67ffeb)
    font_family = Monocraft Nerd Font
    font_size = 72
    position = 0, 100
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 500, 64
    position = 0, -60
    halign = center
    valign = center
    outline_thickness = 2
    outer_color = rgb(f8f8f2)
    inner_color = rgb(191919)
    font_color = rgb(f8f8f2)
    check_color = rgb(a2f300)
    fail_color = rgb(ff025f)
    placeholder_text = Password
    dots_center = true
    rounding = 0
}
